projects:
  - title: Dibattito sul ddL 409
    short-name: ddl 409 urbanistica
       website: https://progetto.ministerodocumentazione.gov.it
    tags:
      - governo del territorio
      - coste
      - consumo di suolo
    documents:
      - title: Documento del progetto
        repository: project-document-doc
      - title: Un altro documento del progetto
        repository: another-project-document-doc

